### ISSUE TITLE
 File loading error when using Windows search function

### ISSUE THREAD

**Issue by rivkms** [sopia-bot/SOPIA#15]
window10에서 프로그램 작동시켰습니다. 버전은 1.11.4입니다.
SOPIA 폴더에서 프로그램을 실행시키는 것이 대부분이나 윈도우 검색 기능을 이용하여 프로그램을 실행시켜보았습니다. 

![이미지 1](https://user-images.githubusercontent.com/61501033/131962295-ca99b7ef-64fc-45cd-bb17-3a5b4991f658.png)

이렇게 작동시킬 경우 프로그램이 잘 작동하는 것처럼 보입니다. 

![이미지 2](https://user-images.githubusercontent.com/61501033/131962390-67872052-cf71-4c63-bc98-5fd1cb52a17c.png)

하지만 code탭을 눌러 코드를 수정하려고 하는 경우

![이미지 3](https://user-images.githubusercontent.com/61501033/131962453-ec6c6a73-6ac6-4cd7-93a7-7afbdd396e56.png)

다음과 같이 코드가 증발하는 버그가 발생하게 됩니다. 

![이미지 4](https://user-images.githubusercontent.com/61501033/131962497-04e647d7-a136-48cb-ae5e-0f7bdbb07c0e.png)

추가적으로 개발자도구에서는 다음과 같은 에러가 발생하고 있고, 소피아는 작동하지 않습니다. 
기존의 방식으로 다시 실행을 시키면 정상 작동을 하게 됩니다.

**Comment by raravel** [comment]
소피아는 파일 접근을 **실행된 경로** 에서 검색하기 때문에, 윈도우 검색 기능으로 실행을 시키면 `C:\Windows\System32`  경로에서 실행되는 걸로 추정됩니다.

즉 소피아 파일이 그곳에 없기 때문에 문제가 생기는 겁니다. 수정 의사 없습니다.
